# Generated by Django 5.1.7 on 2025-03-29 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idCourse', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('date_of_birth', models.DateField()),
                ('premium', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('idLesson', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='compilais.course')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('idCertificate', models.AutoField(primary_key=True, serialize=False)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compilais.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compilais.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('idUserCourses', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='compilais.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='compilais.user')),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UserProgressCourse',
            fields=[
                ('idUserProgress', models.AutoField(primary_key=True, serialize=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_who_completed', to='compilais.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='compilais.user')),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
